[book]
authors = ["David Moles"]
language = "en"
multilingual = false
src = "src"
title = "TTRPG-ML: Sketch for a tabletop role-playing game markup language"

[output.html]
additional-css = ["custom.css"]
