[book]
authors = ["David Moles"]
title = "TTRPG-ML: Sketch for a tabletop RPG markup language"
language = "en"
multilingual = false

[output.html]
additional-css = ["custom.css"]
default-theme = "light"
site-url = "https://dmoles.github.io/ttrpg-ml/"
