[book]
authors = ["David Moles"]
title = "TTRPG•ML: Sketch for a tabletop role-playing game markup language"
language = "en"
multilingual = false

[output.html]
additional-css = ["custom.css"]
site-url = "https://dmoles.github.io/ttrpg-ml/"
